steps:

# Fetch deploy keys for tools repo
- name: 'gcr.io/cloud-builders/gsutil'
  args:
  - cp
  - gs://cloud-marketplace-ops-test-kokoro/deploykeys/googlecloudplatform_marketplace-k8s-app-tools
  - /root/.ssh/googlecloudplatform_marketplace-k8s-app-tools
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Fetch deploy keys for ubbagent repo
- name: 'gcr.io/cloud-builders/gsutil'
  args:
  - cp
  - gs://cloud-marketplace-ops-test-kokoro/deploykeys/googlecloudplatform_ubbagent
  - /root/.ssh/googlecloudplatform_ubbagent
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Fetch key for the github app
- name: 'gcr.io/cloud-builders/gsutil'
  args:
  - cp
  - gs://cloud-marketplace-ops-test-kokoro/appkeys/cloudbuild
  - cloudbuild.pem
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Setup git repo
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - cloudbuild/fetch_submodules.sh
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Set commit as pending
- name: 'gcr.io/$PROJECT_ID/verifier'
  entrypoint: 'bash'
  args:
  - -c
  - |
    cloudbuild/set_commit_status.sh \
      --secret=cloudbuild.pem \
      --issuer=11572 \
      --state=pending \
      --target_url="https://pantheon.corp.google.com/gcr/builds/$BUILD_ID?project=$PROJECT_ID" \
      --description="Running integration tests" \
      --context="google-cloud/builder/integration-test" \
      --repo="$_REPO_NAME" \
      --commit=$COMMIT_SHA
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Run the verification
- name: 'gcr.io/$PROJECT_ID/verifier'
  entrypoint: 'bash'
  dir: 'nginx'
  args:
  - -c
  - |
    gcloud container clusters get-credentials "$_CLUSTER_NAME" --zone "$_CLUSTER_LOCATION"
    make app/verify

# Set commit as succeeded
- name: 'gcr.io/$PROJECT_ID/verifier'
  entrypoint: 'bash'
  args: 
  - -c
  - |
    cloudbuild/set_commit_status.sh \
      --secret=cloudbuild.pem \
      --issuer=11572 \
      --state=success \
      --target_url="https://pantheon.corp.google.com/gcr/builds/$BUILD_ID?project=$PROJECT_ID" \
      --description="Integration tests passed." \
      --context="google-cloud/builder/integration-test" \
      --repo="$_REPO_NAME" \
      --commit=$COMMIT_SHA
  volumes:
  - name: 'ssh'
    path: /root/.ssh
