steps:

- id: Fetch key for the github app
  name: gcr.io/cloud-builders/gsutil
  args:
  - cp
  - gs://cloud-marketplace-ops-test-kokoro/appkeys/cloudbuild
  - cloudbuild.pem

- id: Set commit as pending
  waitFor:
  - Fetch key for the github app
  name: gcr.io/$PROJECT_ID/verifier
  entrypoint: bash
  args:
  - -c
  - |
    cloudbuild/set_commit_status.sh \
      --secret=cloudbuild.pem \
      --issuer=11572 \
      --state=pending \
      --target_url="https://pantheon.corp.google.com/gcr/builds/$BUILD_ID?project=$PROJECT_ID" \
      --description="Running integration tests" \
      --context="google-cloud/builder/integration-test" \
      --repo="$_REPO_NAME" \
      --commit=$COMMIT_SHA

- id: Setup git repo
  waitFor:
  - '-'
  name: gcr.io/$PROJECT_ID/verifier
  entrypoint: bash
  args:
  - -c
  - make submodule/init

- id: Authenticate
  name: gcr.io/cloud-marketplace-tools/k8s/dev:latest
  waitFor:
  - '-'
  args:
  - -e
  - -c
  - gcloud container clusters get-credentials "$_CLUSTER_NAME" --zone "$_CLUSTER_LOCATION"

- id: Build Wordpress
  name: gcr.io/cloud-marketplace-tools/k8s/dev:latest
  waitFor:
  - Setup git repo
  dir: wordpress
  args:
  - -c
  - make clean app/build

- id: Fetch wordpress reporting secret
  name: gcr.io/cloud-builders/gsutil
  args:
  - cp
  - gs://cloud-marketplace-ops-test-kokoro/reporting_secrets/wordpress.yaml
  - reporting-sercret.json

- id: Verify Wordpress
  name: gcr.io/cloud-marketplace-tools/k8s/dev:latest
  waitFor:
  - Build Wordpress
  - Authenticate
  - Fetch wordpress reporting secret
  env:
  - APP_DEPLOYER=$_REGISTRY/example/wordpress/deployer:latest
  - |
    APP_PARAMETERS={
                     "imageWordpress": "$_REGISTRY/example/wordpress:latest",
                     "imageInit": "$_REGISTRY/example/wordpress/init:latest",
                     "imageMysql": "$_REGISTRY/example/wordpress/mysql:latest",
                     "imageUbbagent": "$_REGISTRY/example/wordpress/ubbagent:latest",
                     "reportingSecret": "file://reporting-secret.json",
                     "imageTester": "$_REGISTRY/example/wordpress/tester:latest"
                   }
  args:
  - -c
  - |
    /scripts/driver_internal.sh \
        --deployer="$$APP_DEPLOYER" \
        --parameters="$$APP_PARAMETERS"

- id: Build NGINX
  name: gcr.io/cloud-marketplace-tools/k8s/dev:latest
  waitFor:
  - Setup git repo
  dir: nginx
  args:
  - -c
  - make clean app/build

- id: Verify NGINX
  name: gcr.io/cloud-marketplace-tools/k8s/dev:latest
  waitFor:
  - Build NGINX
  - Authenticate
  env:
  - APP_DEPLOYER=$_REGISTRY/example/nginx/deployer:latest
  - |
    APP_PARAMETERS={
                     "imageNginx.image": "$_REGISTRY/example/nginx:latest",
                     "tester.image": "$_REGISTRY/example/nginx/tester:latest"
                   }
  args:
  - -c
  - |
    /scripts/driver_internal.sh \
        --deployer="$$APP_DEPLOYER" \
        --parameters="$$APP_PARAMETERS"

- id: Set commit as succeeded
  name: gcr.io/$PROJECT_ID/verifier
  waitFor:
  - Verify Wordpress
  - Verify NGINX
  entrypoint: bash
  args:
  - -c
  - |
    cloudbuild/set_commit_status.sh \
      --secret=cloudbuild.pem \
      --issuer=11572 \
      --state=success \
      --target_url="https://pantheon.corp.google.com/gcr/builds/$BUILD_ID?project=$PROJECT_ID" \
      --description="Integration tests passed." \
      --context="google-cloud/builder/integration-test" \
      --repo="$_REPO_NAME" \
      --commit=$COMMIT_SHA
