#!/bin/bash

docker build \
    --build-arg="HELM_DEPENDENCY_BUILD=true" \
    --tag="gcr.io/marketplace-k8s-app-example/deployer_helm_tiller_onbuild/deployer:latest" \
    .

docker push "gcr.io/marketplace-k8s-app-example/deployer_helm_tiller_onbuild/deployer:latest"
