#!/bin/bash

docker run \
  --net=host \
  --mount "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock,readonly" \
  --mount "type=bind,source=${KUBE_CONFIG:-$HOME/.kube},target=/mount/config/.kube,readonly" \
  --mount "type=bind,source=${GCLOUD_CONFIG:-$HOME/.config/gcloud},target=/mount/config/.config/gcloud,readonly" \
  --rm \
  "gcr.io/cloud-marketplace-tools/k8s/dev:sha_7209a962383653c0972f1ecf9b7ae09566157ac6" \
  scripts/install \
      --deployer="gcr.io/marketplace-k8s-app-example/deployer_helm_tiller_onbuild/deployer:latest" \
      --parameters='{
                      "name": "chartmuseum-1",
                      "namespace": "default",
                      "marketplace-integration.image": "gcr.io/marketplace-k8s-app-example/deployer_helm_tiller_onbuild/deployer:latest"
                    }'
