steps:

- id: Setup git repo
  waitFor:
  - '-'
  name: gcr.io/$PROJECT_ID/verifier
  entrypoint: bash
  args:
  - -c
  - make submodule/init

- id: Authenticate
  name: gcr.io/cloud-marketplace-tools/k8s/dev:latest
  waitFor:
  - '-'
  args:
  - -e
  - -c
  - gcloud container clusters get-credentials "$_CLUSTER_NAME" --zone "$_CLUSTER_LOCATION"

- id: Build Wordpress
  name: gcr.io/cloud-marketplace-tools/k8s/dev:latest
  waitFor:
  - '-'
  dir: wordpress
  args:
  - -c
  - make clean app/build

- id: Fetch wordpress reporting secret
  name: gcr.io/cloud-builders/gsutil
  args:
  - cp
  - gs://cloud-marketplace-ops-test-kokoro/reporting_secrets/wordpress.yaml
  - reporting-secret.json

- id: Verify Wordpress
  name: gcr.io/cloud-marketplace-tools/k8s/dev:latest
  waitFor:
  - Build Wordpress
  - Authenticate
  - Fetch wordpress reporting secret
  env:
  - APP_DEPLOYER=$_REGISTRY/example/wordpress/deployer:latest
  - |
    APP_PARAMETERS={
                     "imageWordpress": "$_REGISTRY/example/wordpress:latest",
                     "imageInit": "$_REGISTRY/example/wordpress/init:latest",
                     "imageMysql": "$_REGISTRY/example/wordpress/mysql:latest",
                     "imageUbbagent": "$_REGISTRY/example/wordpress/ubbagent:latest",
                     "reportingSecret": "file://reporting-secret.json",
                     "imageTester": "$_REGISTRY/example/wordpress/tester:latest"
                   }
  args:
  - -x
  - -c
  - |
    /scripts/driver_internal.sh \
        --deployer="$$APP_DEPLOYER" \
        --parameters="$$APP_PARAMETERS"

- id: Build NGINX
  name: gcr.io/cloud-marketplace-tools/k8s/dev:latest
  waitFor:
  - '-'
  dir: nginx
  args:
  - -c
  - make clean app/build

- id: Verify NGINX
  name: gcr.io/cloud-marketplace-tools/k8s/dev:latest
  waitFor:
  - Build NGINX
  - Authenticate
  env:
  - APP_DEPLOYER=$_REGISTRY/example/nginx/deployer:latest
  - |
    APP_PARAMETERS={
                     "imageNginx.image": "$_REGISTRY/example/nginx:latest",
                     "tester.image": "$_REGISTRY/example/nginx/tester:latest"
                   }
  args:
  - -x
  - -c
  - |
    /scripts/driver_internal.sh \
        --deployer="$$APP_DEPLOYER" \
        --parameters="$$APP_PARAMETERS"
