steps:

# Initializations

- id: Initialize git
  name: gcr.io/cloud-builders/git
  args: ['submodule', 'update', '--init', '--recursive']

- id: Get Kubernetes Credentials
  name: gcr.io/cloud-builders/gcloud
  args:
  - container
  - clusters
  - get-credentials
  - "limani-integ"
  - --region
  - "us-central1"
  - --project
  - "$PROJECT_ID"

- id: Copy Kubernetes Credentials
  name: gcr.io/google-appengine/debian9
  entrypoint: bash
  args:
  - -exc
  - |
    mkdir -p /workspace/.kube/
    cp -r $$HOME/.kube/ /workspace/
  waitFor:
  - Get Kubernetes Credentials

- id: Copy gcloud Credentials
  name: gcr.io/google-appengine/debian9
  waitFor:
  - Get Kubernetes Credentials
  entrypoint: bash
  args:
  - -exc
  - |
    mkdir -p /workspace/.config/gcloud/
    cp -r $$HOME/.config/gcloud/ /workspace/.config/

- id: Pull Dev Image
  name: gcr.io/cloud-builders/docker
  waitFor:
  - Initialize git
  entrypoint: bash
  args:
  - -exc
  - |
    TAG="$$(cat MARKETPLACE_TOOLS_TAG)"
    docker pull "gcr.io/cloud-marketplace-tools/k8s/dev:$$TAG"
    docker tag "gcr.io/cloud-marketplace-tools/k8s/dev:$$TAG" "gcr.io/cloud-marketplace-tools/k8s/dev:local"

- id: Initialized
  name: bash
  waitFor:
  - Initialize git
  - Get Kubernetes Credentials
  - Copy Kubernetes Credentials
  - Copy gcloud Credentials
  - Pull Dev Image

# Wordpress Verification

- id: Fetch Wordpress Reporting Secret
  name: gcr.io/cloud-builders/gsutil
  args:
  - cp
  - gs://cloud-marketplace-ops-test-kokoro/reporting_secrets/wordpress.yaml
  - reporting-secret.json

- id: Verify Wordpress
  name: gcr.io/cloud-marketplace-tools/k8s/dev:local
  waitFor:
  - Initialized
  - Fetch Wordpress Reporting Secret
  dir: wordpress
  env:
  - 'KUBE_CONFIG=/workspace/.kube'
  - 'GCLOUD_CONFIG=/workspace/.config/gcloud'
  # Use local Docker network named cloudbuild as described here:
  # https://cloud.google.com/cloud-build/docs/overview#build_configuration_and_build_steps
  - 'EXTRA_DOCKER_PARAMS=--net cloudbuild'
  args:
  - make
  - app/verify

- id: Verify Wordpress Updatable
  name: gcr.io/cloud-marketplace-tools/k8s/dev:local
  waitFor:
  - Initialized
  - Fetch Wordpress Reporting Secret
  dir: wordpress-updatable
  env:
  - 'KUBE_CONFIG=/workspace/.kube'
  - 'GCLOUD_CONFIG=/workspace/.config/gcloud'
  # Use local Docker network named cloudbuild as described here:
  # https://cloud.google.com/cloud-build/docs/overview#build_configuration_and_build_steps
  - 'EXTRA_DOCKER_PARAMS=--net cloudbuild'
  args:
  - make
  - app/verify

# NGINX Verification

- id: Verify NGINX
  name: gcr.io/cloud-marketplace-tools/k8s/dev:local
  waitFor:
  - Initialized
  dir: nginx
  env:
  - 'KUBE_CONFIG=/workspace/.kube'
  - 'GCLOUD_CONFIG=/workspace/.config/gcloud'
  - 'EXTRA_DOCKER_PARAMS=--net cloudbuild'
  # Use local Docker network named cloudbuild as described here:
  # https://cloud.google.com/cloud-build/docs/overview#build_configuration_and_build_steps
  args:
  - make
  - app/verify
