steps:

# Initializations

- id: Initialize git
  name: gcr.io/cloud-builders/git
  args:
  - init

- id: Sync Submodules
  name: gcr.io/cloud-builders/git
  waitFor:
  - Initialize git
  args:
  - submodule
  - sync
  - --recursive

- id: Update Submodules
  name: gcr.io/cloud-builders/git
  waitFor:
  - Sync Submodules
  args:
  - submodule
  - update
  - --init
  - --recursive

- id: Get Kubernetes Credentials
  name: gcr.io/cloud-builders/gcloud
  args:
  - container
  - clusters
  - get-credentials
  - "limani-integ"
  - --region
  - "us-central1"

- id: Initialized
  name: bash
  waitFor:
  - Update Submodules
  - Get Kubernetes Credentials

# Wordpress Verification

- id: Fetch Wordpress Reporting Secret
  name: gcr.io/cloud-builders/gsutil
  args:
  - cp
  - gs://cloud-marketplace-ops-test-kokoro/reporting_secrets/wordpress.yaml
  - reporting-secret.json

- id: Build Wordpress
  name: gcr.io/cloud-marketplace-tools/k8s/dev:latest
  waitFor:
  - Initialized
  dir: wordpress
  args:
  - -c
  - make clean app/build

- id: Verify Wordpress
  name: gcr.io/cloud-marketplace-tools/k8s/dev:latest
  waitFor:
  - Initialized
  - Build Wordpress
  - Fetch Wordpress Reporting Secret
  env:
  - APP_DEPLOYER=gcr.io/cloud-marketplace-ops-test/example/wordpress/deployer:latest
  - |
    APP_PARAMETERS={
                     "imageWordpress": "gcr.io/cloud-marketplace-ops-test/example/wordpress:latest",
                     "imageInit": "gcr.io/cloud-marketplace-ops-test/example/wordpress/init:latest",
                     "imageMysql": "gcr.io/cloud-marketplace-ops-test/example/wordpress/mysql:latest",
                     "imageUbbagent": "gcr.io/cloud-marketplace-ops-test/example/wordpress/ubbagent:latest",
                     "reportingSecret": "file://reporting-secret.json",
                     "imageTester": "gcr.io/cloud-marketplace-ops-test/example/wordpress/tester:latest"
                   }
  args:
  - -x
  - -c
  - |
    /scripts/driver_internal.sh \
        --deployer="$$APP_DEPLOYER" \
        --parameters="$$APP_PARAMETERS"
