steps:

- id: Build helm/
  name: gcr.io/cloud-builders/docker
  dir: helm/
  args:
  - build
  - --build-arg=MARKETPLACE_TOOLS_TAG=sha_9423c06cbc7fc5a74421fe5f582577bdc640fa28
  - --build-arg=HELM_DEPENDENCY_BUILD=true
  - --tag=gcr.io/marketplace-k8s-app-example/helm/deployer:latest
  - .

- id: Build envsubst/
  name: gcr.io/cloud-builders/docker
  dir: envsubst/
  args:
  - build
  - --build-arg=MARKETPLACE_TOOLS_TAG=sha_9423c06cbc7fc5a74421fe5f582577bdc640fa28
  - --tag=gcr.io/marketplace-k8s-app-example/envsubst/deployer:latest
  - .
