apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.APP_INSTANCE_NAME }}
  labels:
    application.k8s.io/name: "{{ .Values.APP_INSTANCE_NAME }}"
    app: {{ template "nginx.name" . }}
    chart: {{ template "nginx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "nginx.name" . }}
    release: {{ .Release.Name }}
