apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels: &Labels
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: nginx
    app: {{ template "nginx.name" . }}
    chart: {{ template "nginx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: *Labels
  template:
    metadata:
      labels: *Labels
    spec:
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.imageNginx.repo }}:{{ .Values.imageNginx.tag }}"
          imagePullPolicy: {{ .Values.imageNginx.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
