properties:
  NAME:
    type: string
    x-google-marketplace:
      type: NAME
  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  IMAGE_NGINX:
    type: string
    # TODO(ruela): use proper nginx path when it is ready
    default: gcr.io/cloud-marketplace/e2e-testing/k8s-app/nginx:latest
    x-google-marketplace:
      type: IMAGE
required:
- NAME
- NAMESPACE
- IMAGE_NGINX
