properties:
  APP_INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME
  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  IMAGE_WORDPRESS:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  IMAGE_INIT:
    type: string
    default: $REGISTRY/init:$TAG
    x-google-marketplace:
      type: IMAGE
  IMAGE_MYSQL:
    type: string
    default: $REGISTRY/mysql:$TAG
    x-google-marketplace:
      type: IMAGE
  IMAGE_UBBAGENT:
    type: string
    default: $REGISTRY/ubbagent:$TAG
    x-google-marketplace:
      type: IMAGE
  DB_PASSWORD:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 16
  serverReplicas:
    title: Server replicas
    type: int
    default: 1
    minimum: 1
    maximum: 128
  blogTitle:
    title: Blog title
    description: WordPress requires a blog title for setup. This can be changed later.
    type: string
    maxLength: 128
    pattern: '[A-Za-z0-9 -]+'
required:
- APP_INSTANCE_NAME
- NAMESPACE
- IMAGE_WORDPRESS
- IMAGE_INIT
- IMAGE_MYSQL
- IMAGE_UBBAGENT
- DB_PASSWORD
