application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  deployerImage:
    type: string
    x-google-marketplace:
      type: DEPLOYER_IMAGE
  imageWordpress:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: imageWordpressRepo
            after: imageWordpressTag
  imageInit:
    type: string
    default: $REGISTRY/init:$TAG
    x-google-marketplace:
      type: IMAGE
  imageMysql:
    type: string
    default: $REGISTRY/mysql:$TAG
    x-google-marketplace:
      type: IMAGE
  imageUbbagent:
    type: string
    default: $REGISTRY/ubbagent:$TAG
    x-google-marketplace:
      type: IMAGE
  dbPassword:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 16
  customString:
    title: Blog title
    description: WordPress requires a blog title for setup. This can be changed later.
    type: string
    default: 'My blog'
    maxLength: 128
    pattern: '[A-Za-z0-9 -]+'
  customInteger:
    title: Server replicas
    type: integer
    default: 1
    minimum: 1
    maximum: 128
  customBoolean:
    title: A custom boolean parameter.
    type: boolean
    default: false
  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET
  istioEnabled:
    type: boolean
    x-google-marketplace:
      type: ISTIO_ENABLED
  ingressAvailable:
    type: boolean
    x-google-marketplace:
      type: INGRESS_AVAILABLE
  certificate:
    type: string
    x-google-marketplace:
      type: TLS_CERTIFICATE
      tlsCertificate:
        generatedProperties:
          base64EncodedPrivateKey: base64EncodedPrivateKey
          base64EncodedCertificate: base64EncodedCertificate
  serviceType:
    type: string
    enum:
    - LoadBalancer
    - ClusterIP
    default: ClusterIP
    title: Service type of WordPress
required:
- name
- namespace
- deployerImage
- imageWordpress
- imageInit
- imageMysql
- imageUbbagent
- dbPassword
- customString
- customInteger
- customBoolean
- reportingSecret
- serviceType
form:
- widget: help
  description: My arbitrary <i>description</i>
x-google-marketplace:
  clusterConstraints:
    resources:
    - replicas: 3
      requests:
        cpu: 1
      affinity:
        simpleNodeAffinity:
          type: REQUIRE_ONE_NODE_PER_REPLICA
    istio:
      type: OPTIONAL
