#!/bin/bash

cd $(dirname "$0")

export REGISTRY="${REGISTRY:-gcr.io/$(gcloud config get-value project)}"
export MARKETPLACE_TOOLS_TAG="${MARKETPLACE_TOOLS_TAG:-$(cat ../MARKETPLACE_TOOLS_TAG)}"
export DEPLOYER_IMAGE="$REGISTRY/envsubst/deployer:$MARKETPLACE_TOOLS_TAG"
export NAME="application-1"
export NAMESPACE="default"
export IMAGE_MYSQL="$REGISTRY/envsubst/mysql:$MARKETPLACE_TOOLS_TAG"
export IMAGE_WORDPRESS="$REGISTRY/envsubst/wordpress:$MARKETPLACE_TOOLS_TAG"
export PARAMETERS="{
              \"APP_INSTANCE_NAME\": \"$NAME\",
              \"NAMESPACE\": \"$NAMESPACE\",
              \"IMAGE_MYSQL\": \"$IMAGE_MYSQL\",
              \"IMAGE_WORDPRESS\": \"$IMAGE_WORDPRESS\"
            }"

function _setup_dev() {
  export temp="$(mktemp -d)"
  trap 'rm -rf "$temp"' EXIT
  docker run "gcr.io/cloud-marketplace-tools/k8s/dev:$MARKETPLACE_TOOLS_TAG" cat /scripts/dev > "$temp/dev"
  chmod +x "$temp/dev"
}

function build() {
  docker build \
      --build-arg "MARKETPLACE_TOOLS_TAG=$MARKETPLACE_TOOLS_TAG" \
      --tag="$DEPLOYER_IMAGE" \
      .

  docker push "$DEPLOYER_IMAGE"

	docker pull launcher.gcr.io/google/mysql5
	docker tag launcher.gcr.io/google/mysql5 "$IMAGE_MYSQL"
	docker push "$IMAGE_MYSQL"

	docker pull launcher.gcr.io/google/wordpress4-php7-apache:latest
	docker tag launcher.gcr.io/google/wordpress4-php7-apache:latest "$IMAGE_WORDPRESS"
	docker push "$IMAGE_WORDPRESS"
}

function install() {
	_setup_dev

  "$temp/dev" \
    /scripts/install \
        --deployer="$DEPLOYER_IMAGE" \
        --parameters="$PARAMETERS"
}

function uninstall() {
  kubectl delete "applications/$NAME" --namespace "$NAMESPACE"
}

function verify() {
	_setup_dev

  "$temp/dev" \
    /scripts/verify \
        --deployer="$DEPLOYER_IMAGE" \
        --parameters="$PARAMETERS"
}


"$@"
