#!/bin/bash

cd $(dirname "$0")

export MARKETPLACE_TOOLS_TAG="sha_7209a962383653c0972f1ecf9b7ae09566157ac6"
export DEPLOYER_IMAGE="gcr.io/marketplace-k8s-app-example/envsubst/deployer:latest"
export NAME="application-1"
export NAMESPACE="default"
export PARAMETERS="{
              \"name\": \"$NAME\",
              \"namespace\": \"$NAMESPACE\",
              \"reportingSecret\": \"gs://cloud-marketplace-ops-test-kokoro/reporting_secrets/wordpress.yaml\"
            }"

function _setup_dev() {
  export temp="$(mktemp -d)"
  trap 'rm -rf "$temp"' EXIT
  docker run "gcr.io/cloud-marketplace-tools/k8s/dev:$MARKETPLACE_TOOLS_TAG" cat /scripts/dev > "$temp/dev"
  chmod +x "$temp/dev"
}

function build() {
  docker build \
      --tag="$DEPLOYER_IMAGE" \
      .

  docker push "$DEPLOYER_IMAGE"
}

function install() {
	_setup_dev

  "$temp/dev" \
    /scripts/install \
        --deployer="$DEPLOYER_IMAGE" \
        --parameters="$PARAMETERS"
}

function uninstall() {
  kubectl delete "applications/$NAME" --namespace "$NAMESPACE"
}

function verify() {
	_setup_dev

  "$temp/dev" \
    /scripts/verify \
        --deployer="$DEPLOYER_IMAGE" \
        --parameters="$PARAMETERS"
}


$@
