application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  imageWordpress:
    type: string
    default: launcher.gcr.io/google/wordpress4-php5-apache:latest
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: imageWordpressRepo
            after: imageWordpressTag
  imageInit:
    type: string
    # TODO: Reference a different image.
    default: gcr.io/marketplace-k8s-app-example/example/wordpress/init@sha256:3fc5a3267c43f47fc7282cdc3fb2417945ff0f41618c1402867bd755d031124d
    x-google-marketplace:
      type: IMAGE
  imageMysql:
    type: string
    default: launcher.gcr.io/google/mysql5:latest
    x-google-marketplace:
      type: IMAGE
  imageUbbagent:
    type: string
    default: gcr.io/cloud-marketplace-tools/metering/ubbagent:sha_dfb8b727bd23a7e48b6b4904f4fa2aad43634607
    x-google-marketplace:
      type: IMAGE
  dbPassword:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 16
  customString:
    title: Blog title
    description: WordPress requires a blog title for setup. This can be changed later.
    type: string
    default: 'My blog'
    maxLength: 128
    pattern: '[A-Za-z0-9 -]+'
  customInteger:
    title: Server replicas
    type: integer
    default: 1
    minimum: 1
    maximum: 128
  customBoolean:
    title: A custom boolean parameter.
    type: boolean
    default: false
  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET
required:
- name
- namespace
- imageWordpress
- imageInit
- imageMysql
- imageUbbagent
- dbPassword
- customString
- customInteger
- customBoolean
- reportingSecret
form:
- widget: help
  description: My arbitrary <i>description</i>
